# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab432d531fa4f05edee9ca3598c395ab4db6dfdbad1529aeff90f024985d4c62dd47b883fe07ff332ac9b086c37f6f22c0b2a089966cfd88ace262d0cbd43d6

test:
  secret_key_base: 4124ddd72a3aa1ab945f7178334d0e9fbdbd1c3ebd3fc09f25e45c5366389cc51c790aaea68005ed84afe24a4ecc9836d8bccf9003601c6f88af876ee6df6c43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
